### ISSUE TITLE
Cool idea but nothing changed for me

### ISSUE THREAD

**Issue by gabipintea** [gadgetchnnel/lovelace-card-preloader#5]
Hi! Great work doing this. Saw a lot of people complaining about the lazy-load feature after 0.107.* upgrade. Thanks for everything! Still not working for me though. I have no custom cards, just a vertical stack with two conditionals that used to work before upgrading to 0.107.7. Right now, everything works as expected after a refresh. If i switch the condition, the other conditional card does not appear, until i press the configure ui button at the top. After that works as expected.

So I found this preloader, installed it using HACS, added to resources by pressing the buttons on the notification pop-ups. Added everything in my mind, trying to make it work in raw configuration editor before anything else:

```
preload:
  - vertical-stack
  - horizontal-stack
  - entities
  - entity
  - entity-button
  - conditional
  - picture-elements
  - picture-entity
```
Looking in the console, everything seems fine( i know the 'preload:' is deprecated), it shows that all the types are preloaded, no errors at all. Still nothing changes in the behaviour of my setup. Any idea?
```
cards:
  - card:
      elements:
        - entity: switch.bar_lights
          icon: 'mdi:lightbulb'
          style:
            left: 63%
            top: 30%
          tap_action:
            action: toggle
          type: state-icon
      image: /local/images/Smarthome-parter-alloff.png
      type: picture-elements
    conditions:
      - entity: switch.bar_lights
        state: 'off'
    type: conditional
  - card:
      elements:
        - entity: switch.bar_lights
          icon: 'mdi:lightbulb'
          style:
            left: 63%
            top: 30%
          tap_action:
            action: toggle
          type: state-icon
      image: /local/images/Smarthome-parter-bar.png
      type: picture-elements
    conditions:
      - entity: switch.bar_lights
        state: 'on'
    type: conditional
type: vertical-stack
```
